[general]
import = ["/home/chester/.config/alacritty/themes/alacrytheme/themes/rose-pine-dawn.toml"]

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 15.0

[font.normal]
family = "0xproto Nerd Font Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[bell]
animation = "EaseOutCirc"
duration = 2
color = "#ff0055"
command = "xkbbell"

[selection]
save_to_clipboard = false

[window]
decorations = "None"
opacity = 0.85
padding = {x = 5, y = 5}
