[general]
import = ["/home/chester/.config/alacritty/themes/wallust-colors.toml"]

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[font]
size = 17.0

[font.normal]
family = "Iosevka Nerd Font Mono"
# Hack Nerd Font Mono
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
decorations = "None"
opacity = 0.75
padding = {x = 25, y = 25}
dynamic_title = true
