scan_timeout = 10
add_newline = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[line_break]
#disabled = true

[status]
symbol = "🔴"
format = '[\[$symbol $common_meaning$signal_name$maybe_int $status\]]($style) '
map_symbol = true
disabled = false

[username]
style_user = "bold green"
show_always = true
